# Essential site config
[build]
  base = "/"
  command = "yarn build"
  publish = "dist"
  functions = "server/lambda"

[build.environment]
  GO_IMPORT_PATH="github.com/netlify/next-function"
  GO_VERSION="1.15"
  NODE_VERSION = "16.13.2"

    
# Site info, used for the 1-Click deploy page
[template.environment]
  # STATUSKIT_PAGE_TITLE = "Web Check"
  # STATUSKIT_COMPANY_LOGO = "https://raw.githubusercontent.com/Lissy93/dashy/master/docs/assets/logo.png"
  # STATUSKIT_SUPPORT_CONTACT_LINK = "https://github.com/lissy93/dashy"
  # STATUSKIT_RESOURCES_LINK = "https://dashy.to/docs"

# Redirect the Node endpoints to serverless functions
# [[redirects]]
#   from = "/status-check"
#   to = "/.netlify/functions/cloud-status-check"
#   status = 301
#   force = true
# [[redirects]]
#   from = "/config-manager/*"
#   to = "/.netlify/functions/not-supported"
#   status = 301
#   force = true
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/web-check"
  status = 301
  force = true
[[redirects]]
  from = "/find-url-ip"
  to = "/.netlify/functions/find-url-ip"
  status = 301
  force = true
[[redirects]]
  from = "/lighthouse-report"
  to = "/.netlify/functions/lighthouse-report"
  status = 301
  force = true
  
# For router history mode, ensure pages land on index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  

# Set any security headers here
[[headers]]
  for = "/*"
  [headers.values]
  # Uncomment to enable Netlify user control. Requires premium plan.
  # Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"


  