# Essential site config
[build]
  base = "/"
  command = "yarn build"
  publish = "build"
  functions = "server/lambda"

[build.environment]
  NODE_VERSION = "16.16.0"

    
# Site info, used for the 1-Click deploy page
[template.environment]
  STATUSKIT_PAGE_TITLE = "Web Check"
  STATUSKIT_COMPANY_LOGO = "https://raw.githubusercontent.com/Lissy93/web-check/master/public/apple-touch-icon.png"
  STATUSKIT_SUPPORT_CONTACT_LINK = "https://github.com/lissy93/web-check"

# Redirect the Node endpoints to serverless functions
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/web-check"
  status = 301
  force = true
[[redirects]]
  from = "/find-url-ip"
  to = "/.netlify/functions/find-url-ip"
  status = 301
  force = true
[[redirects]]
  from = "/lighthouse-report"
  to = "/.netlify/functions/lighthouse-report"
  status = 301
  force = true
[[redirects]]
  from = "/ssl-check"
  to = "/.netlify/functions/ssl-check"
  status = 301
  force = true  
[[redirects]]
  from = "/get-headers"
  to = "/.netlify/functions/get-headers"
  status = 301
  force = true
[[redirects]]
  from = "/get-cookies"
  to = "/.netlify/functions/get-cookies"
  status = 301
  force = true
[[redirects]]
  from = "/get-dns"
  to = "/.netlify/functions/get-dns"
  status = 301
  force = true
[[redirects]]
  from = "/read-robots-txt"
  to = "/.netlify/functions/read-robots-txt"
  status = 301
  force = true
[[redirects]]
  from = "/follow-redirects"
  to = "/.netlify/functions/follow-redirects"
  status = 301
  force = true
[[redirects]]
  from = "/get-txt"
  to = "/.netlify/functions/get-txt"
  status = 301
  force = true  
[[redirects]]
  from = "/server-status"
  to = "/.netlify/functions/server-status"
  status = 301
  force = true
  
# For router history mode, ensure pages land on index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  

# Set any security headers here
[[headers]]
  for = "/*"
  [headers.values]
  # Uncomment to enable Netlify user control. Requires premium plan.
  # Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"


  